// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import NestedAgents from "./nested_agents_controller"
application.register("nested-agents", NestedAgents)

import NestedEmployees from "./nested_employees_controller"
application.register("nested-employees", NestedEmployees)

import NestedPolicies from "./nested_policies_controller"
application.register("nested-policies", NestedPolicies)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
