default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ichra_assesment_development

test:
  <<: *default
  database: ichra_assesment_test

production:
  <<: *default
  database: ichra_assesment_production
  username: ichra_assesment
  password: <%= ENV['ICHRA_ASSESMENT_DATABASE_PASSWORD'] %>
